# Generated by Django 2.1.5 on 2021-11-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('phn', models.PositiveIntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('1', 'MALE'), ('2', 'FEMALE')], max_length=2)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
